### ISSUE TITLE
raw trace stops

### ISSUE THREAD

**Issue by vid** [ixmaps/ixnode#9]
to some destinations the raw trace will stop after a certain number of hops (with timeouts)?

**Comment by agamba** [comment]
In my tests I've also experienced this and discovered that the raw-sockets responds much faster to the non responding routers than the platform command. By "raw trace" do you mean nodejs raw-socket module or platform tracerotue. For delays and eventually crashing due to the non responsive platform traceroute, a temporary solution might be to disable the execution/collection of platform output until we manage to prevent this from finishing a TR submission

**Comment by vid** [comment]
This is referring to the raw sockets implementation. If you're seeing platform traceroute problems they should be reported in a separate issue.

One host where this problem manifested frequently was hc-sc.gc.ca. I just tried it and it stops at pass 4, hop 19, though it stopped sooner in my other testing.
